### PR TITLE
Updated v3.9.0

### PR DESCRIPTION
**Pull request by isreehari**
I have updated it v3.9.0 and it's working fine.

### CODE REVIEW

**Comment by ryannix123** [comment]
Hey @isreehari this works great! Thanks so much for updating this.

I noticed at the end of the install there was one specific error that looks to be related to using Let's Encrypt. Are the deployment scripts now using Let's Encrypt?

`error: couldn't get https://console.apps.cic.edu:8443/.well-known/oauth-authorization-server: unexpected response status 403`

If so, can I assume this error is because I haven't specifc the web console port to listen on 443 instead of the default 8443?

**Comment by ryannix123** [comment]
One more thing. When I changed the web console port before running the install to 443, at the end of the install I get:
missing service (service "webconsole" not found)
missing route (service "webconsole" not found)

Evidentally this is related to 3.9 https://nology.de/openshift-3-9-missing-webconsole.html

**Comment by isreehari** [comment]
No that's not 100% true because I can able to run and access all the containers. I got the web console as well.

**Comment by ryannix123** [comment]
Was it on the default 8443, though? My first install using your repo worked perfectly on 8443. It was my subsequent attempt to switch the master to 443 that reported back that error.

**Comment by isreehari** [comment]
Oh okay, let me try with 443 and get back to you. 

Thanks,
Hari

**Comment by ryannix123** [comment]
Thanks, @isreehari . SHouldn't we be able to pass this in the inventory file, though?

https://docs.openshift.com/container-platform/3.6/install_config/install/advanced_install.html#configuring-host-port

and

https://docs.openshift.com/container-platform/3.9/install_config/install/advanced_install.html#configuring-host-port

**Comment by isreehari** [comment]
Hi @ryannix123 , ansible-playbook use the /etc/ansible/hosts as default place for configuration instructions but we defined it in inventory.ini file.  If we don't pass the inventory.ini file to your ansible-playbook installation then it will take configuration from /etc/ansible/hosts so what ever we define in our inventory.ini ansible-playbook suppose to configure our openshift origin cluster. Here it would be nice if a senior member help us to use the 443 port for master @gshipley

**Comment by marekjelen** [comment]
Thanks

**Comment by marekjelen** [comment]
Regarding the web console port

https://github.com/gshipley/installcentos/issues/40

**Pull request merged**
