### PR TITLE
Added node selector tag for template_services_broker

### PR DESCRIPTION
**Pull request by slaterx**
Added fix for bugzilla #1538616

### CODE REVIEW

**Comment by ryannix123** [comment]
@slaterx Unfortunately, the service template broker is still not deploying for me. The catalog has only eight items in it.

**Comment by marekjelen** [comment]
@ryannix123 can you please add a screenshot and possible Ansible output from the installation to https://github.com/gshipley/installcentos/issues/30 ? Thanks!

**Comment by marekjelen** [comment]
@slaterx the linked issue says that

```
'template_service_broker_selector' which defaults to '{"region":"infra"}'
```

have you run into problem without explicitly stating the label? The problem in the issue seems be that Wolfgang had non-standard label for `infra` nodes - `env` instead of `region`, which should not be our case.

**Comment by slaterx** [comment]
@marekjelen not adding the node selector in ansible was giving me asb/tsb issues, even with ansible playbook finishing successfully.  With the node selector, the template list was populated. Let’s wait for @ryannix123’s reply and I will test with his config.

**Comment by ryannix123** [comment]
Here is my inventory.ini file:
`[OSEv3:children]
masters
nodes
etcd

[masters]
129.105.244.30 openshift_ip=129.105.244.30 openshift_schedulable=true

[etcd]
129.105.244.30 openshift_ip=129.105.244.30

[nodes]
129.105.244.30 openshift_ip=129.105.244.30 openshift_schedulable=true openshift_node_labels="{'region': 'infra', 'zone': 'default'}"

[OSEv3:vars]
ansible_ssh_user=root
enable_excluders=False
enable_docker_excluder=False
ansible_service_broker_install=False

containerized=True
os_sdn_network_plugin_name='redhat/openshift-ovs-multitenant'
openshift_disable_check=disk_availability,docker_storage,memory_availability,docker_image_availability

openshift_node_kubelet_args={'pods-per-core': ['10']}

deployment_type=origin
openshift_deployment_type=origin

openshift_release=v3.7.1
openshift_pkg_version=v3.7.1
openshift_image_tag=v3.7.1
openshift_service_catalog_image_version=v3.7.1
template_service_broker_image_version=v3.7.1
openshift_metrics_image_version=v3.7.1
#openshift_logging_image_version=v3.7.1

osm_use_cockpit=true

openshift_metrics_install_metrics=True
openshift_logging_install_logging=True

openshift_master_identity_providers=[{'name': 'htpasswd_auth', 'login': 'true', 'challenge': 'true', 'kind': 'HTPasswdPasswordIdentityProvider', 'filename': '/etc/origin/master/htpasswd'}]

openshift_public_hostname=console.cloudapps.northwestern.edu
openshift_master_default_subdomain=apps.cloudapps.northwestern.edu
openshift_master_api_port=8443
openshift_master_console_port=8443`

Without explicitly adding 'template_service_broker_selector' which defaults to '{"region":"infra"}' to the file, it still failed:
`TASK [openshift_logging : pulling down signing items from host] ******************************************************************
changed: [129.105.244.30] => (item=ca.crt)
changed: [129.105.244.30] => (item=ca.key)
changed: [129.105.244.30] => (item=ca.serial.txt)
failed: [129.105.244.30] (item=ca.crl.srl) => {"changed": false, "item": "ca.crl.srl", "msg": "file not found: /etc/origin/logging/ca.crl.srl"}
changed: [129.105.244.30] => (item=ca.db)
	to retry, use: --limit @/root/installcentos/openshift-ansible/playbooks/byo/config.retry

PLAY RECAP ***********************************************************************************************************************
129.105.244.30             : ok=793  changed=263  unreachable=0    failed=1   `

**Comment by slaterx** [comment]
Hi,

I test with yours and the following config:

```bash
[OSEv3:children]
masters
nodes
etcd

[masters]
172.31.2.1 openshift_ip=172.31.2.1 openshift_schedulable=true

[etcd]
172.31.2.1 openshift_ip=172.31.2.1

[nodes]
172.31.2.1 openshift_ip=172.31.2.1 openshift_schedulable=true openshift_node_labels="{'region': 'infra', 'zone': 'default'}"

[OSEv3:vars]
ansible_ssh_user=root
enable_excluders=False
enable_docker_excluder=False
ansible_service_broker_install=False

containerized=True
os_sdn_network_plugin_name='redhat/openshift-ovs-multitenant'
openshift_disable_check=disk_availability,docker_storage,memory_availability,docker_image_availability

openshift_node_kubelet_args={'pods-per-core': ['10']}

deployment_type=origin
openshift_deployment_type=origin

openshift_release=v3.7.1
openshift_pkg_version=v3.7.1
openshift_image_tag=v3.7.1
openshift_service_catalog_image_version=v3.7.1
template_service_broker_image_version=v3.7.1
template_service_broker_selector={"region":"infra"}
openshift_metrics_image_version=v3.7.1
#openshift_logging_image_version=v3.7.1

osm_use_cockpit=true

openshift_metrics_install_metrics=True
openshift_logging_install_logging=False

openshift_master_identity_providers=[{'name': 'htpasswd_auth', 'login': 'true', 'challenge': 'true', 'kind': 'HTPasswdPasswordIdentityProvider', 'filename': '/etc/origin/master/htpasswd'}]

openshift_public_hostname=console.172.31.2.1.nip.io
openshift_master_default_subdomain=apps.172.31.2.1.nip.io
openshift_master_api_port=8443
openshift_master_console_port=8443
```

And both worked fine.

Can you provide OS, ansible and python versions?

Thanks,
Gleidson

**Pull request merged**
