### PR TITLE
Make the script interactive for variables

### PR DESCRIPTION
**Pull request by koenhendriks**
Instead of manually running export commands, this extension of the script will just ask for the variables when the script runs. It will still use the default values when the user leaves the prompt blank.

vtvdcs

### CODE REVIEW

**Comment by marekjelen** [comment]
@gshipley

**Comment by marekjelen** [comment]
Hi, thanks for the contribution ... could you please introduce some kind of variable, e.g.

```
export INTERACTIVE="no"
```

so that people can run the script as well in an automated way?

thanks

**Comment by koenhendriks** [comment]
Yeah sure, that's a good idea,. I'll take a spin at it later this week.

**Comment by koenhendriks** [comment]
I've added a `-a` flag for automation and updated the Readme.md to reflect this. 

Let me know what you think.

**Comment by koenhendriks** [comment]
@marekjelen

**Pull request merged**
