### PR TITLE
Parameterized API_PORT for master API port

### PR DESCRIPTION
**Pull request by slaterx**
This change allows the user to select whether to use the default 8443 or to declare a different port (like 443) for his deployment. It's useful when the default clashes in the local machine.

I also applied the fix from https://bugzilla.redhat.com/show_bug.cgi?id=1538616.

### CODE REVIEW

**Comment by ryannix123** [comment]
Hi @slaterx, thanks for updating these!

I tried adding template_service_broker_selector={"env":"infra"} to the inventory.ini file, however, I'm still not getting the service broker to deploy properly. Also, I tried changing the export API_PORT=${API_PORT:="443"} in the install-openshift.ini but received cert errors after the install completed. What am I doing incorrectly?

**Comment by marekjelen** [comment]
@ryannix123 @slaterx going to look into this today / tomorrow

**Comment by slaterx** [comment]
If you're performing an all-in-one install, it's possible that the 443 is assigned to the router. In my case, I wanted the API to listen on 5000 since 8443 is used by another process.

**Comment by marekjelen** [comment]
@slaterx can you, please, resolve the conflict and move the broker selector into separate PR?

I need to look into the selector, as the node should be labeled `region: infra` and so should match the default selector as discussed in the issue

```
'template_service_broker_selector' which defaults to '{"region":"infra"}'
```

https://github.com/gshipley/installcentos/blob/master/inventory.ini#L13

**Comment by slaterx** [comment]
@marekjelen sure I will sort it out.

**Comment by slaterx** [comment]
Done.

**Comment by marekjelen** [comment]
Thanks!

**Comment by ryannix123** [comment]
@marekjelen and @slaterx, thanks for doing this so quickly. However, I'm still getting this error:

failed: [129.105.244.30] (item=ca.crl.srl) => {"changed": false, "item": "ca.crl.srl", "msg": "file not found: /etc/origin/logging/ca.crl.srl"}

**Pull request merged**
